name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install Nix
        uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v8
        if: ${{ secrets.CACHIX_AUTH_TOKEN != '' }}
        with:
          name: kf-website
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build
        id: build
        run: |
          nix build .
          echo "::set-output name=dist::$(readlink result)"

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kf-website-${{ github.sha }}
          path: ${{ steps.build.outputs.dist }}
